CREATE OR REPLACE TRIGGER RNS_DATA_SALARIO_MUDANCA
BEFORE UPDATE OF SALARY
ON EMPLOYEES
FOR EACH ROW
DECLARE	
	ex EXCEPTION;
BEGIN
	IF MONTHS_BETWEEN(sysdate, :OLD.hire_date) < 1 THEN
		RAISE ex;
	END IF;
	EXCEPTION
		WHEN ex THEN
			RAISE_APPLICATION_ERROR(-20001, 'Aumento de salário com menos de um mes de contratação!');
END;
/

	
	